version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: "postgres_db"
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    restart: always
    env_file:
      - .env
    networks:
      - postgres-network

  server:
    image: myimage/tests:latest
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

volumes:
  pgdata:
